#!/usr/bin/env bash
# Configures a new Ubuntu machine by installing Nginx,
# which should be listening on port 80 and serve a page
# that returns the Hello World string.

echo "Updating and installing Nginx..."
apt-get update -y -qq && apt-get install nginx -y

echo "Starting Nginx service..."
service nginx start

echo "Allowing Nginx on firewall..."
ufw allow 'Nginx HTTP'

echo "Setting ownership and permissions for /var/www..."
chown -R "$USER:$USER" /var/www/html
chmod -R 755 /var/www

echo "Backing up the default index page..."
cp -f /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

echo "Creating new index page with 'Hello World!'..."
echo "Hello World!" > /var/www/html/index.nginx-debian.html

echo "Restarting Nginx service..."
service nginx restart

echo "Nginx setup completed successfully! ✅"
